import localFont from "next/font/local";
import "./globals.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faFacebookF,
  faInstagram,
  faSnapchatGhost,
  faPinterestP,
  faTwitter,
  faLinkedinIn,
} from "@fortawesome/free-brands-svg-icons";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* Conteúdo da página */}
        <main className="flex-grow">{children}</main>

        {/* Rodapé */}
        <footer className="bg-teal-600 text-white text-center py-4">
          <p>Find me on social media.</p>
          <div className="flex justify-center space-x-4 mt-2">
            <a
              href="https://www.instagram.com/"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Instagram"
            >
              <FontAwesomeIcon
                icon={faInstagram}
                className="w-5 h-5 text-white hover:text-gray-300"
              />
            </a>
            <a
              href="https://x.com/"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="Twitter"
            >
              <FontAwesomeIcon
                icon={faTwitter}
                className="w-5 h-5 text-white hover:text-gray-300"
              />
            </a>
            <a
              href="https://www.linkedin.com/in/alden-fachetti/"
              target="_blank"
              rel="noopener noreferrer"
              aria-label="LinkedIn"
            >
              <FontAwesomeIcon
                icon={faLinkedinIn}
                className="w-5 h-5 text-white hover:text-gray-300"
              />
            </a>
          </div>
          <p className="mt-4">
            Powered by{" "}
            <a
              href="https://www.linkedin.com/in/alden-fachetti/"
              target="_blank"
              rel="noreferrer"
              className="underline"
            >
              Gabriel Fachetti
            </a>
          </p>
        </footer>
      </body>
    </html>
  );
}
